jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests --batch-mode --no-transfer-progress

      - name: Notify Discord on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📣 New Pull Request created: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.actor }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_PULL_REQUEST }}

      - name: Notify Discord on Push Build Success
        if: github.event_name == 'push' && success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ Build successful on branch ${{ github.ref_name }} by ${{ github.actor }}. Commit: ${{ github.sha }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_PULL_REQUEST }}

      - name: Notify Discord on Push Build Failure
        if: github.event_name == 'push' && failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ Build failed on branch ${{ github.ref_name }} by ${{ github.actor }}. Commit: ${{ github.sha }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_PULL_REQUEST }}
